/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.favorito.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.favorito.model.Favorito;
import com.favorito.model.FavoritoModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Favorito service. Represents a row in the &quot;favoritos_itens&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link FavoritoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FavoritoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FavoritoImpl
 * @see Favorito
 * @see FavoritoModel
 * @generated
 */
@ProviderType
public class FavoritoModelImpl extends BaseModelImpl<Favorito>
	implements FavoritoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a favorito model instance should use the {@link Favorito} interface instead.
	 */
	public static final String TABLE_NAME = "favoritos_itens";
	public static final Object[][] TABLE_COLUMNS = {
			{ "favoritoId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "favoritos_itenscol", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("favoritoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("favoritos_itenscol", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table favoritos_itens (favoritoId LONG not null primary key,userId LONG,favoritos_itenscol VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table favoritos_itens";
	public static final String ORDER_BY_JPQL = " ORDER BY favorito.favoritoId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY favoritos_itens.favoritoId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.favorito.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.favorito.model.Favorito"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.favorito.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.favorito.model.Favorito"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.favorito.service.util.ServiceProps.get(
				"lock.expiration.time.com.favorito.model.Favorito"));

	public FavoritoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _favoritoId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFavoritoId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _favoritoId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Favorito.class;
	}

	@Override
	public String getModelClassName() {
		return Favorito.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("favoritoId", getFavoritoId());
		attributes.put("userId", getUserId());
		attributes.put("favoritos_itenscol", getFavoritos_itenscol());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long favoritoId = (Long)attributes.get("favoritoId");

		if (favoritoId != null) {
			setFavoritoId(favoritoId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String favoritos_itenscol = (String)attributes.get("favoritos_itenscol");

		if (favoritos_itenscol != null) {
			setFavoritos_itenscol(favoritos_itenscol);
		}
	}

	@Override
	public long getFavoritoId() {
		return _favoritoId;
	}

	@Override
	public void setFavoritoId(long favoritoId) {
		_favoritoId = favoritoId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getFavoritos_itenscol() {
		if (_favoritos_itenscol == null) {
			return "";
		}
		else {
			return _favoritos_itenscol;
		}
	}

	@Override
	public void setFavoritos_itenscol(String favoritos_itenscol) {
		_favoritos_itenscol = favoritos_itenscol;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Favorito.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Favorito toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Favorito)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FavoritoImpl favoritoImpl = new FavoritoImpl();

		favoritoImpl.setFavoritoId(getFavoritoId());
		favoritoImpl.setUserId(getUserId());
		favoritoImpl.setFavoritos_itenscol(getFavoritos_itenscol());

		favoritoImpl.resetOriginalValues();

		return favoritoImpl;
	}

	@Override
	public int compareTo(Favorito favorito) {
		long primaryKey = favorito.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Favorito)) {
			return false;
		}

		Favorito favorito = (Favorito)obj;

		long primaryKey = favorito.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Favorito> toCacheModel() {
		FavoritoCacheModel favoritoCacheModel = new FavoritoCacheModel();

		favoritoCacheModel.favoritoId = getFavoritoId();

		favoritoCacheModel.userId = getUserId();

		favoritoCacheModel.favoritos_itenscol = getFavoritos_itenscol();

		String favoritos_itenscol = favoritoCacheModel.favoritos_itenscol;

		if ((favoritos_itenscol != null) && (favoritos_itenscol.length() == 0)) {
			favoritoCacheModel.favoritos_itenscol = null;
		}

		return favoritoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{favoritoId=");
		sb.append(getFavoritoId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", favoritos_itenscol=");
		sb.append(getFavoritos_itenscol());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("com.favorito.model.Favorito");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>favoritoId</column-name><column-value><![CDATA[");
		sb.append(getFavoritoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>favoritos_itenscol</column-name><column-value><![CDATA[");
		sb.append(getFavoritos_itenscol());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Favorito.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Favorito.class, ModelWrapper.class
		};
	private long _favoritoId;
	private long _userId;
	private String _favoritos_itenscol;
	private Favorito _escapedModel;
}